name: General Formatting

on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches: 
      - main
    paths:
      - '**.md'
      - '**.ipynb'

jobs:
  check-broken-links-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run Check broken paths
        run: |
          BROKEN_PATHS=$(python ./.github/markdown_checker.py --dir './' --func 'check_broken_paths')
          echo "BROKEN_PATHS<<EOF" >> $GITHUB_ENV
          echo "$BROKEN_PATHS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Leave broken paths comment
        if: ${{ env.BROKEN_PATHS != '' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              We have automatically detected the following broken relative paths in your lessons.
              Please check the file paths and associated broken paths inside them.
              # Check Broken Paths
              ${{ env.BROKEN_PATHS }}
              `
            })  
          run: exit 1
